### ISSUE TITLE
(bug): plugin installation Error: Pod command failed with exit code 1

### ISSUE THREAD

**Issue by dmacasero** [EinfachHans/cordova-plugin-advanced-imagepicker#12]
# Bug Report

**Current Behavior:**
Adding the plugin throws an error on ios platform:
`
Running command: pod install --verbose
Failed to install 'cordova-plugin-advanced-imagepicker': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Cordova/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`

**Expected Behavior:**
Adding the plugin works on ios without error

**Steps to reproduce:**
1. Create Ionic Project
2. Add Cordova ios platform
3. cordova plugin add cordova-plugin-advanced-imagepicker

**Environment information:**

- Cordova CLI version 
	- cordova 10.0.0
- Cordova platform version
	- ios 6.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-advanced-imagepicker 1.2.0 "AdvancedImagePicker"
- Dev machine OS and version, e.g.
    - OSX
        Mac OS X
        Version: 10.15.5
        Build Version: 19F101`

**Comment by EinfachHans** [comment]
please try to run `pod repo update` before

**Comment by dmacasero** [comment]
You run this after `cordova prepare ios` ?

**Comment by EinfachHans** [comment]
just run it once and repeat the build steps

**Comment by EinfachHans** [comment]
Closed due inactivity

**Comment by scyclops** [comment]
I found that adding <preference name="SwiftVersion" value="5.3" /> to my cordova app config.xml file before installing the cordova-plugin-advanced-imagepicker fixed the problem for me.
