### ISSUE TITLE
(feature-request): Add Sort Option in the File Browser to sort by name or Date.

### ISSUE THREAD

**Issue by lochehong** [EinfachHans/cordova-plugin-advanced-imagepicker#13]
# Feature request

- A descriptive title 
Add Sort Option in the File Browser to sort by name or Date.

- A description of the problem you're trying to solve, including why you think this is a problem
Currently it's hard to upload a document in many pictures without the pictures sorting properly

- An overview of the suggested solution
Add a drop down to allow changing how the files are sorted.

- Use case: why should this be implemented?
So I can upload the files in the correct intended order rather than a random order

Also please keep the file names for the output so that we can sort the files accordingly too.

**Comment by EinfachHans** [comment]
Seems like the Libraries i use in this plugin don't return the filename 🤔

iOS Issue: https://github.com/Yummypets/YPImagePicker/issues/179
Android doesn't seem do have an open issue for that: https://github.com/ParkSangGwon/TedImagePicker

Without the native libraries to support that i can't implement that, so please open feature requests there and open another one in here after they developed this.
