### ISSUE TITLE
(bug): Permission camera for Android usage

### ISSUE THREAD

**Issue by giantjeaks** [EinfachHans/cordova-plugin-advanced-imagepicker#14]
# Bug Report

**Current Behavior:**
When I click to open imagepicker panel it showed camera icon and I try to open it to take a photo but the application close its own

**Expected Behavior:**
Take a photo and return success

**Steps to reproduce:**
When I click to open imagepicker panel it showed camera icon and I try to open it to take a photo but the application close its own

**Screenshots:**
![image](https://user-images.githubusercontent.com/35835084/107006574-e7ca2380-67c3-11eb-9aa8-3c5bcd8f0066.png)

**Environment information:**

- Cordova CLI version => 10.0.0
- Cordova platform version => Android@^9.0.0
- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-advanced-imagepicker 1.2.0 "AdvancedImagePicker"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-whitelist 1.3.4 "Whitelist"

cordova-plugin-camera 5.0.1 "Camera"
- Dev machine OS and version, e.g.
    - Windows 10
        OS 1909 Build 18363.1316

**Additional information**
I think I need to allow permission for my application because after I manually allow it in setting it works fine.
 Anyone can please provide a way to config it? I've tried [this](https://stackoverflow.com/a/41152761/10876897) but it doesn't work

Update even I tried to install cordova-plugin-camera which is grant camera permission by default still have no luck :(

**Comment by erikramalho** [comment]
We solved this issue by adding cordova-plugin-android-permissions and asking for the permissions :
`checkAndroidCameraPermission() {
    this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.CAMERA).then(
      result => {
        if (!result || !result.hasPermission) {
          this.androidPermissions.requestPermissions([this.androidPermissions.PERMISSION.CAMERA, this.androidPermissions.PERMISSION.GET_ACCOUNTS]);
        }
      },
      err => this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.CAMERA)
    );
  }`

**Comment by EinfachHans** [comment]
This Plugin doesn't support permission request. Use Android Permissions or Diagnostics Plugin instead!

**Comment by giantjeaks** [comment]
Thank you guys all for helping :)
