### ISSUE TITLE
(feature-request): Get files with EXIF data on Ios

### ISSUE THREAD

**Issue by deifemu** [EinfachHans/cordova-plugin-advanced-imagepicker#16]
I need the exif data on the pictures, especially the date the picture was taken. 
This is working perfectly in android but Ios seems to strip exif data for security reasons. 

Is there any chance we can get the files with the exif data included?
Or expose the functionallity of YPImagePicker 
print(photo.exifMeta) // Print exif meta data of original image.

**Comment by EinfachHans** [comment]
How do you currently get this Data on Android?

**Comment by deifemu** [comment]
it is included in the file. I just read in on server side. 
There is a lot of discussion on getting the data for the camera plugin. 
I think it is included now. There is also a camera-with-exif plugin.
I will try to get it using the plugin Cordova Exif Utility
But I could not get it to work until now

**Comment by EinfachHans** [comment]
I will have a look!

**Comment by deifemu** [comment]
It looks like this is all I need:
AdvancedImagePicker.swift: line 112
"exif": photo.exifMeta?.description ?? "-"


    func handleResult(items: [YPMediaItem], asBase64: Bool, asJpeg: Bool) {
        var array = [] as Array;
        for item in items {
            switch item {
            case .photo(let photo):
                let encodedImage = self.encodeImage(image: photo.image, asBase64: asBase64, asJpeg: asJpeg);
                array.append([
                    "type": "image",
                    "isBase64": asBase64,
                    "src": encodedImage,
                    "exif": photo.exifMeta?.description ?? "-"
                ]);

**Comment by EinfachHans** [comment]
Feel free to open a PR. But this should work on Android too!

**Comment by deifemu** [comment]
yes and converting the exif dictionary to a string is certainly not the best way to do it. but my swift is really limited. actually this was just my first try on it :)
