### ISSUE TITLE
(bug): Version 1.3.0 causing error on iOS - jpegData has been renamed to UIImageJPEGRepresentation

### ISSUE THREAD

**Issue by erikramalho** [EinfachHans/cordova-plugin-advanced-imagepicker#17]
# Bug Report

**Current Behavior:**
Xcode can't compile iOS due errors.

**Expected Behavior:**
Compile it without errors

**Steps to reproduce:**
Install the latest plugin version and try to generate  the project

**Screenshots:**
 
<img width="1537" alt="Captura de Tela 2021-04-09 às 13 20 40" src="https://user-images.githubusercontent.com/5274068/114211190-b4785200-9936-11eb-9812-99420c6470aa.png">
add screenshots to help explain your problem.  

**Environment information:**

- Cordova CLI version: 10.0.0
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
	     Installed platforms:
  android 9.0.0
  ios 6.2.0
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`

**Additional information**

**Comment by EinfachHans** [comment]
What Version of xCode do you have installed? 🤔

**Comment by erikramalho** [comment]
<img width="555" alt="Captura de Tela 2021-04-09 às 13 32 29" src="https://user-images.githubusercontent.com/5274068/114212333-184f4a80-9938-11eb-970c-5452efbc6a7a.png">
Sorry, forgot to put this info

**Comment by EinfachHans** [comment]
I will check that later thanks. I know i did this change because i integrated this Plugin in an Capacitor V3 App and this was required 🤔 For know please downgrade to the version below or change it manually

**Comment by erikramalho** [comment]
Hi @EinfachHans sorry to bother you with this issue. I think it was something with my env. I've cleaned up everything and the errors disapeared.

**Comment by EinfachHans** [comment]
@erikramalho Thanks for the Update! I had no time to check but if it disappears: Great 😃 does make more sense haha. If you have any more problems feel free to open an Issue

**Comment by mival** [comment]
Hi @erikramalho I have same issue now with Xcode Version 13.0 (13A233). How does you solved it?

**Comment by mival** [comment]
It seems that problem was with SWIFT versions. For me solution was use `SWIFT_VERSION=5 cordova platform add ios@latest` while adding platform. After that `pod install` finished successfully and xcode build works
