### ISSUE TITLE
(bug):DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.

### ISSUE THREAD

**Issue by zoranmil** [EinfachHans/cordova-plugin-advanced-imagepicker#18]
# Bug Report
DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.
**Current Behavior:**

DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.
**Expected Behavior:**

**Steps to reproduce:**

**Screenshots:**

**Environment information:**

- Cordova CLI version 
	- `cordova 9.10`
- Cordova platform version
	- `cordova platform android`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
    - cordova-plugin-advanced-imagepicker 1.3.1 "AdvancedImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`

**Additional information**

**Comment by EinfachHans** [comment]
What Version of Android Studio are u using?

**Comment by EinfachHans** [comment]
Closed due inactivity

**Comment by zoranmil** [comment]
Android studio 3.1
