### ISSUE TITLE
(bug):need install command or installation error

### ISSUE THREAD

**Issue by qwert321** [EinfachHans/cordova-plugin-advanced-imagepicker#19]
# Bug Report

**Current Behavior:**
$cordova plugin add https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker.git
to install the plugin, but with errors:
Installing "cordova-plugin-advanced-imagepicker" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-advanced-imagepicker" for ios
Installing "cordova-plugin-add-swift-support" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-advanced-imagepicker': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/hh/repo/tenant.group/client/app/landlord/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
pod: Command failed with exit code 1

**Expected Behavior:**

**Steps to reproduce:**

**Screenshots:**

**Environment information:**

- Cordova CLI version 
	- `cordova -v`
	10.0.0
	
- Cordova platform version
	- `cordova platform ls`
	  ios 6.2.0

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
    cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-imagepicker 1.3.1 "AdvancedImagePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
        ProductName:	macOS
ProductVersion:	11.2.2

    - Windows 10
        - `winver`

**Additional information**

**Comment by EinfachHans** [comment]
Can you try to run `pod repo update` within the ios platform and install again?

**Comment by scyclops** [comment]
I found that adding <preference name="SwiftVersion" value="5.3" /> to my cordova app config.xml file before installing the cordova-plugin-advanced-imagepicker fixed the problem for me.
