### ISSUE TITLE
Error - Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by demait** [EinfachHans/cordova-plugin-advanced-imagepicker#2]
Hello everyone,

I have the following problem:

I have included the ImagePicker in my Ionic app.

But as soon as I start the app and try to start the ImagePicker using the .present function, I get the following output in the console, but nothing opens

Error - Cannot read property 'apply' of undefined

Maybe one of you can help me?

**Comment by EinfachHans** [comment]
Please open an [new Issue (Bug Report)](https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker/issues/new?assignees=&labels=triage&template=bug_report.md&title=%28bug%29%3A) and use the template, otherwise i have to less information to help you!
