### ISSUE TITLE
(feature-request): upgrade YPImagePicker dependency from 4.4.0 to 4.5.0

### ISSUE THREAD

**Issue by ryan-bunkr** [EinfachHans/cordova-plugin-advanced-imagepicker#21]
Hey @EinfachHans, I'm very appreciative that you put this plugin together. One issue I'm having in iOS when enabling multiple image selection, is that the first image is selected by default when opening the picker.

This bug is actually in YPImagePicker itself, and was resolved in release 4.5.0.
https://github.com/Yummypets/YPImagePicker/issues/575

I tested updating the YPImagePicker version in the plugin.xml file locally from 4.4.0 to 4.5.0 and verified that it resolves the issue.
Here are its release notes: https://github.com/Yummypets/YPImagePicker/releases/tag/4.5.0

Do you see any issue updating this dependency?
If there's anything I can do to help, let me know. Thanks!

**Comment by EinfachHans** [comment]
If you can create a small PR it would be faster, but i think i can do this the next week 😀

**Comment by EinfachHans** [comment]
Added in `1.4.0`
