### ISSUE TITLE
Capacitor Support for this plugin

### ISSUE THREAD

**Issue by Saqib92** [EinfachHans/cordova-plugin-advanced-imagepicker#22]
# Feature request
Please Add Support for Capacitor to select multiple Images and Video.

**Comment by EinfachHans** [comment]
This Plugin works with Capacitor, i'm using it myself.

What's the error that do you have?

**Comment by Saqib92** [comment]
Its not Getting installed. 
Installation Command:
>cordova plugin add https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker.git

Error:
>Current working directory is not a Cordova-based project.

**Comment by EinfachHans** [comment]
You are trying to add this Plugin tk Capacitor via a `CORDOVA add`? How would this ever work

**Comment by Saqib92** [comment]
> You are trying to add this Plugin tk Capacitor via a `CORDOVA add`? How would this ever work

how can I install it? is there NPM available for this plugin?

**Comment by EinfachHans** [comment]
https://www.npmjs.com/package/cordova-plugin-advanced-imagepicker
