### ISSUE TITLE
Path of image is not correct (no filename and extension)

### ISSUE THREAD

**Issue by cmarian5** [EinfachHans/cordova-plugin-advanced-imagepicker#25]
Hello,

The result returned from the plugin is:
content://media/external/images/media/681
But I need to get the real path of the image containing both filename and extension in order to upload it.

How I can get the real path?

**Comment by clarklight** [comment]
@cmarian5 Did you manage to figure out how to get the file URI path?

**Comment by clarklight** [comment]
I managed to get it working with the filepath plugin, but that plugin is deprecated, but thats the method to get it to get the absolute file path, and upload.

**Comment by Mr-Anonymous** [comment]
I noticed the same issue too. It seems to work in some Android devices whereas some Android 12/13 devices shows the path as: `[filepath](content:\/\/media\/external\/images\/media\/1000059240)` which fails when uploading to the server since it is unable to identify the file type.
