### ISSUE TITLE
(bug): Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by demait** [EinfachHans/cordova-plugin-advanced-imagepicker#3]
# Bug Report

**Current Behavior:**

I have included the ImagePicker in my Ionic app.

But as soon as I start the app and try to start the ImagePicker using the .present function, I get the following output in the console, but nothing opens

ERROR TypeError: Cannot read property 'apply' of undefined

**Expected Behavior:**

I expect the Select Image dialog to open.

**Steps to reproduce:**
Every time I call the function .present

**Environment information:**

- Cordova CLI version: 
  -5.4.16
- Cordova platform version:  
  -android 8.1.0
- Plugins & versions installed in project (including this plugin)
    - card.io.cordova.mobilesdk 2.1.0 "CardIO"
       com.paypal.cordova.mobilesdk 3.5.0 "PayPalMobile"
       cordova-plugin-device 2.0.2 "Device"
       cordova-plugin-imagegallery 2.0.4 "cordova-plugin-imagegallery"
       cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
       cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
       cordova-plugin-splashscreen 5.0.2 "Splashscreen"
       cordova-plugin-statusbar 2.4.2 "StatusBar"
       cordova-plugin-whitelist 1.3.3 "Whitelist"

- Dev machine OS and version, e.g.
    - Windows 10
        - `winver` : 1903

Sorry for my first ticket.
Here is a description of the problem in the correct layout

**Comment by EinfachHans** [comment]
You don't have the Plugin installed correctly i think. I the Plugin List i can't see it?

**Comment by demait** [comment]
Thanks a lot, the plugin was really not properly integrated.

But now I have another error:

As soon as I try to build the app the following error appears:


FAILURE: Build failed with an exception.

* Where:
Script 'F:\Projekte\mymomentsPayPalTest\platforms\android\cordova-plugin-advanced-imagepicker\starter-build.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Could not find method buildFeatures() for arguments [starter_build_b8i90lghhpeewesa8ctcfcman$_run_closure1$_closure2@625a595d] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

**Comment by demait** [comment]
Thanks a lot, the plugin was really not properly integrated.

But now I have another error:

As soon as I try to build the app the following error appears:

* Where:
Script '{ProjectPath}\platforms\android\cordova-plugin-advanced-imagepicker\starter-build.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Could not find method buildFeatures() for arguments [starter_build_b8i90lghhpeewesa8ctcfcman$_run_closure1$_closure2@625a595d] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

**Comment by EinfachHans** [comment]
Have you followed the [Install Guide](https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker#install) and set everything correctly?

**Comment by demait** [comment]
Yes, the steps are all executed correctly.

**Comment by EinfachHans** [comment]
I found this: https://stackoverflow.com/questions/58692811/error-when-adding-buildfeatures-in-build-gradle-file

Which Android Studio Version do you use?

**Comment by EinfachHans** [comment]
Close die inactivity
