### ISSUE TITLE
(feature-request): set max targetHeight/targetWidth for images

### ISSUE THREAD

**Issue by mrbdrm** [EinfachHans/cordova-plugin-advanced-imagepicker#36]
it will be prefect if we can set the targetHeight or targetWidth for the selected images like we can do in Cordova camera plugin

**Comment by EinfachHans** [comment]
What are these options used for?

**Comment by mrbdrm** [comment]
> What are these options used for?

limit the dimensions of the selected image. so the image get resized if its bigger than the supplied high or width

**Comment by EinfachHans** [comment]
You can do this yourself in your app after getting the image from this library
