### ISSUE TITLE
(bug): ios 15.3 Only See header/main Photo

### ISSUE THREAD

**Issue by itbeyond** [EinfachHans/cordova-plugin-advanced-imagepicker#39]
# Bug Report

**Current Behavior:**

When I open the Gallery selection on ios 15.3 on an iPad after selecting allow all files - I can only see the first one in the larger window and there are no thumbnail images showing at all. I did a pod update to YPImagePicker 5.2.1 however this also did not fix it and made a styling error (but this is not the bug) so went back to 4.5.0. See screenshots below.

**Expected Behavior:**

If I run this on ios 15.2 it works correctly and shows the thumbnails of the rest of the library but on 15.3 I only get as per the screenshots.

**Steps to reproduce:**

Current config as called 
{ showCameraTile: false, mediaType: "IMAGE", max: 5, asJpeg: true }

**Screenshots:**

![img1](https://user-images.githubusercontent.com/1870615/151762416-4a54cb20-c738-42b4-a7d0-1975384ec112.png)
Shows the number of items in each section of the iPad
![img2](https://user-images.githubusercontent.com/1870615/151762427-85d11598-1f78-48d7-accc-3a1646f9712a.png)
Shows all I can see when in a section - NO thumbnails.

**Environment information:**

- Cordova CLI version 
	- `cordova -v`
	- 11.0.0
- Cordova platform version
	- `cordova platform ls`
	- ios 6.2.0

**Additional information**

I just loaded up the picker in portrait mode and low and behold the thumbnails appear - so it would seem that this picker does not work in landscape mode or is there a simple solution?

Here is a screenshot from using portrait mode on the same iPad, same versions of everything!
![img3](https://user-images.githubusercontent.com/1870615/151763917-add48abe-f2e1-45b6-9e83-f73bedf14bb1.png)

**Comment by EinfachHans** [comment]
I use this Library underneath: https://github.com/Yummypets/YPImagePicker

please try create an issue there

**Comment by itbeyond** [comment]
Yeah just found it - https://github.com/Yummypets/YPImagePicker/issues/550 

I will have to drop or update this plugin (shame seems to be the best around at the moment) as I must support Landscape mode. I may try pluging in this ios picker as referenced in the issue above - https://github.com/hyperoslo/ImagePicker

**Comment by EinfachHans** [comment]
Mhh okay, i would also try to comment on that PR that this is an issue for you as well.

I can't switch to the other package in here as it doesn't support videos and stuff for example 😕

**Comment by itbeyond** [comment]
I understand and wonder if there is something else out there. I do not really need video support for this app but I have some others that would benefit from using this plugin that also video. I am on a serious timeline right now. I was in beta release testing when this came up.

**Comment by itbeyond** [comment]
OK for anyone that must have Landscape images and/or video I reverted to the last Media Picker tool I was using and can confirm this solves the Landscape selection issues use :- https://github.com/DmcSDK/cordova-plugin-mediaPicker or my fork that puts the media files into the Document directory on iOS vs the temp directory to get around app reboots losing the media files https://github.com/itbeyond/cordova-plugin-mediaPicker.
