### ISSUE TITLE
(feature-request): Remove NSCameraUsageDescription,NSPhotoLibraryUsageDescription, NSMicrophoneUsageDescription from the plugin.xml

### ISSUE THREAD

**Issue by brunolau** [EinfachHans/cordova-plugin-advanced-imagepicker#41]
Hardcoded info.plist setting overrides my settings provided in config.xml and results in app store rejection. I believe each user should handle this in his/her config.xml as each app has different usage scenario

**Comment by tempo-riz** [comment]
For the same reason as @brunolau and since the the repo was last updated 7 months ago I cloned it removing those hardcoded permissions,
for anyone struggling you can use it like this:
cordova plugin add https://github.com/tempo-riz/cordova-plugin-advanced-imagepicker

**Comment by EinfachHans** [comment]
`V1.6.0` released 😊
