### ISSUE TITLE
pngData and jpegData are depreciated 

### ISSUE THREAD

**Issue by gchokeen** [EinfachHans/cordova-plugin-advanced-imagepicker#44]
# Bug Report

'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'
'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'

```
 if(asJpeg) {
            imageData = image.jpegData(compressionQuality: 0.8)! as NSData;
        } else {
            imageData = image.pngData()! as NSData;
        }
```

fix

```
 if(asJpeg) {
            imageData = UIImageJPEGRepresentation(image,0.8)! as NSData;
        } else {
            imageData = UIImagePNGRepresentation(image)! as NSData;
        }
```

**Current Behavior:**

**Expected Behavior:**

**Steps to reproduce:**

**Screenshots:**

**Environment information:**

- Cordova CLI version 
	- `11.0.0`
- Cordova platform version
	- `Installed platforms: ios 6.2.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-imagepicker 1.4.0 "AdvancedImagePicker"
cordova-plugin-camera 6.0.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file-transfer 2.0.0-dev "File Transfer"
cordova-plugin-file 7.0.0 "File"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 4.0.0 "Capture"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.5 "ImagePicker"
cordova-plugin-x-socialsharing 6.0.3 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`

**Additional information**

**Comment by EinfachHans** [comment]
![Bildschirmfoto 2022-08-16 um 10 05 21](https://user-images.githubusercontent.com/20899975/184829634-acd5aff1-23a5-4033-9ee5-25a3a5acf69b.png)

It's the other way around 😃
