### ISSUE TITLE
(bug): plugin installation Error: Pod command failed with exit code 1

### ISSUE THREAD

**Issue by drogerie21** [EinfachHans/cordova-plugin-advanced-imagepicker#5]
# Bug Report

**Current Behavior:**
Trying to add the plugin throws an error on ios platform:

```log
Failed to install 'cordova-plugin-advanced-imagepicker': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Cordova/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Trying to install the pod on the ios platform (pod install) leads to this error:
```log
Installing PryntTrimmerView (4.0.2)
Installing SteviaLayout (4.7.3)
Installing YPImagePicker (4.3.1)
[!] Unable to determine Swift version for the following pods:

- `SteviaLayout` does not specify a Swift version and none of the targets (`HybridForms`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Expected Behavior:**
Adding the plugin works on ios platform without error

**Steps to reproduce:**
1) add cordova ios platform
2) add cordova plugin  -> cordova plugin add cordova-plugin-advanced-imagepicker

**Screenshots:**

**Environment information:**

- Cordova CLI version 
	- cordova 10.0.0
- Cordova platform version
	- Installed platforms: ios 6.1.1

- Plugins & versions installed in project (including this plugin)
    - com.bez4pieci.cookies 0.0.1 "Cookies"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 3.0.0 "Advanced HTTP plugin"
cordova-plugin-advanced-imagepicker 1.0.1 "AdvancedImagePicker"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cookies 0.0.1 "CookiesPlugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-scanner 4.2.5 "Scan"
cordova-plugin-file-opener2 3.0.4 "File Opener2"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-secure-storage-echo 5.0.1 "SecureStorage"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 5.0.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"

- Dev machine OS and version, e.g.
    - OSX
        - ProductName:    Mac OS X
           ProductVersion: 10.15.6
           BuildVersion:   19G2021

**Comment by EinfachHans** [comment]
Mhh i'm not having this issue. Please try to run `pod repo update` && `pod install` inside the **platforms/ios** folder

**Comment by drogerie21** [comment]
this is exactly what i´ve done before. "pod install" throws this error:
```log
Installing PryntTrimmerView (4.0.2)
Installing SteviaLayout (4.7.3)
Installing YPImagePicker (4.3.1)
[!] Unable to determine Swift version for the following pods:

- `SteviaLayout` does not specify a Swift version and none of the targets (`HybridForms`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by EinfachHans** [comment]
So you also have run `pod repo update`?

Can you please create a new Project and only add this Plugin and check if it happns too? If so, please provide a repo to it

**Comment by drogerie21** [comment]
Hi, 

i´ve just created an repo: a cordova project, only plugin is your plugin, same Error as before.
here you can find the repo: https://github.com/drogerie21/cordovaImagePickerTest

Thanks for your help!

**Comment by kesit** [comment]
Hi,
I have the same problem mentioning SteviaLayout doesn't specify Swift version.
My solution is:
- remove ios platform: cordova platform remove ios
- add <preference name="UseSwiftLanguageVersion" value="5" /> in config.xml
- create ios platform: cordova platform add ios --> will throw error in my case
- prepare ios platform again: cordova prepare ios
- go to ios platform and run: pod install

Now it doesn't throw any error about Swift Version from SteviaLayout anymore.

But I have new problem when building ios:

`UIKit.UIImagePNGRepresentation:2:13: note: 'UIImagePNGRepresentation' was obsoleted in Swift 3
public func UIImagePNGRepresentation(_ image: UIImage) -> Data?`

**Comment by EinfachHans** [comment]
@drogerie21 i just checked out your repo, i can build and run it 🤔

**Comment by jossela** [comment]
Same issue ... I tried to run `pod repo update` it's not working for me !

**Comment by orenkatz-lp** [comment]
Same issue for me

**Comment by orenkatz** [comment]
same issue for me, any luck?

**Comment by scyclops** [comment]
I found that adding <preference name="SwiftVersion" value="5.3" /> to my cordova app config.xml file before installing the cordova-plugin-advanced-imagepicker fixed the problem for me.
