### ISSUE TITLE
(bug): YPImagePicker@5.2.1 fails to build in XCode 15

### ISSUE THREAD

**Issue by maxymczech** [EinfachHans/cordova-plugin-advanced-imagepicker#59]
# Bug Report

**Current Behavior:**
This plugin fails to build in XCode 15.

**Expected Behavior:**
The plugin should build successfully in XCode 15.

**Additional information**
`YPImagePicker@5.2.2` was released 2 weeks ago.

**Comment by srinich-dev** [comment]
Same issue was seen for me. Please let me know how to resolve this

**Comment by fmendoza** [comment]
try adding this line to the config.xml

```
<preference name="deployment-target" value="12.0" />
```

**Comment by marija06** [comment]
Any news about this? I get the same error, I tried adding <preference name="deployment-target" value="12.0" /> to config.xml and it did not fix the issue.
