### ISSUE TITLE
(bug): iOS: correct screens per media type config

### ISSUE THREAD

**Issue by erikramalho** [EinfachHans/cordova-plugin-advanced-imagepicker#7]
# Feature request

Enable users to choose
1 - only photo gallery and photo (camera)
2 - only video gallery and video (camera)
3 - all gallery, photo and video camera

something like this:
if(showCameraTile) { if(mediaType != "IMAGE") { screens.append(.photo); } else if(mediaType != "VIDEO") { screens.append(.video); } else { screens.append(.photo); screens.append(.video); } }

I believe it should give users more controls of the options...

**Comment by EinfachHans** [comment]
I think this is only iOS relevant as the Option to select android and video at the same time doesn't work on android as i mentioned in the quirks

**Comment by EinfachHans** [comment]
Agreed that this should be the normal behavior, it's more a bug currently

**Comment by EinfachHans** [comment]
Should work correctly in `1.2.0` 😊
