### ISSUE TITLE
(feature-request):Expose videotrim as option (Boolean)

### ISSUE THREAD

**Issue by erikramalho** [EinfachHans/cordova-plugin-advanced-imagepicker#8]
# Feature request

 By default, iOS plugin comes with this option set to false. Expose a way So the users could choose to enable it.

Even the if android plug-in doesn’t enable something like this, I think iOS users could use it.

**Comment by EinfachHans** [comment]
Currently i can't activate this 😔 With the trim feature a "select a cover" feature comes with automatically. I only will enable this option, if the underlaying library will implement my feature request to disable this

**Comment by erikramalho** [comment]
Got it... let’s keep an eye on it.
