### ISSUE TITLE
(feature-request): Expose a thumbnail (small base64) in response

### ISSUE THREAD

**Issue by erikramalho** [EinfachHans/cordova-plugin-advanced-imagepicker#9]
# Feature request

It would be very useful if a small/thumbnail base64 attribute could be added in the returned object. Lots of apps display a list of images selected by the user. Small base64 files will avoid freeze ou crash the app. 

It's not something "MUST HAVE" for the plugin, but will enable even less work for the developers.

**Comment by EinfachHans** [comment]
So you mean that the app should create a thumbnail for every inage by refactoring it?

**Comment by erikramalho** [comment]
Yeah, something like that. I believe the iOS plugin already does that. Not sure about Android plugin.

It’s not a “must have” feature. But for sure could be useful to display as a preview. Think about it 😇

**Comment by EinfachHans** [comment]
I don't see the iOS Plugin doing this - but you can do this yourself? Showing many base64 images crashes your app? what about the file uri u requested or using a virtual scroll with lazy image loading?
